apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyx-stack.fullname" . }}-inference-model
  labels:
    {{- range .Values.inferenceCapability.deployment.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  replicas: {{ .Values.inferenceCapability.deployment.replicas }}
  selector:
    matchLabels:
      {{- range .Values.inferenceCapability.deployment.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range .Values.inferenceCapability.podLabels }}
        {{ .key }}: {{ .value }}
        {{- end }}
    spec:
      containers:
      - name: model-server-inference
        image: "{{ .Values.inferenceCapability.deployment.image.repository }}:{{ .Values.inferenceCapability.deployment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.inferenceCapability.deployment.image.pullPolicy }}
        command: [ "uvicorn", "model_server.main:app", "--host", "0.0.0.0", "--port", "{{ .Values.inferenceCapability.deployment.containerPorts.server }}" ]
        ports:
        - name: model-server
          containerPort: {{ .Values.inferenceCapability.deployment.containerPorts.server }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.config.envConfigMapName }}
        env:
          {{- include "onyx-stack.envSecrets" . | nindent 12}}
        volumeMounts:
        {{- range .Values.inferenceCapability.deployment.volumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
      {{- range .Values.inferenceCapability.deployment.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}
